panvc3:
  output_prefix: 'panvc3'
  reads_1: '../reads/HG002_HiSeq30x_subsampled_R1.fastq.gz'
  reads_2: '../reads/HG002_HiSeq30x_subsampled_R2.fastq.gz'
  reference: '../reference/hs37d5.fa'
  chromosomes: ['1']
  known_variants_prefix: '../known-variants/ALL.chr'
  known_variants_suffix: '.phase3_shapeit2_mvncall_integrated_v5b.20130502.genotypes.vcf'
